[default.app]
name = "{{cookiecutter.project_slug}}"
version = "0.0.1"
env = "default"
debug = false

[development.app]
dynaconf_merge = true
env = "dev"
debug = true

[testing.app]
dynaconf_merge = true
env = "test"
debug = false

[production.app]
dynaconf_merge = true
env = "prod"
debug = false
