default:
  logging:
    version: 1
    handlers:
      richHandler:
        class: rich.logging.RichHandler
        level: DEBUG
    loggers:
      {{cookiecutter.project_slug}}:
        level: DEBUG
        handlers: [richHandler]
      root:
        level: DEBUG
        handlers: [richHandler]
